extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-config-clean-order
rules:
  alpha-value-notation: null
  color-no-hex: true
  color-function-notation: null
  declaration-no-important: true
  declaration-block-no-redundant-longhand-properties: null
  function-no-unknown: null
  import-notation: null
  max-nesting-depth: 3
  media-query-no-invalid: null
  no-descending-specificity: null
  no-empty-source: null
  order/properties-alphabetical-order: null
  scss/percent-placeholder-pattern: null
  selector-class-pattern: null
  selector-no-qualifying-type: null
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  string-quotes: null

overrides:
  - files: ["**/*.scss"]
    customSyntax: "postcss-scss"
