extends:
  - stylelint-config-standard
rules:
  alpha-value-notation: null
  declaration-empty-line-before: null
  at-rule-no-unknown: null
  media-query-no-invalid: null
  color-function-notation: null
  declaration-no-important: true
  function-no-unknown: null
  import-notation: null
  no-descending-specificity: null
  no-empty-source: null
  rule-empty-line-before: null
  selector-class-pattern: null
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  string-quotes: null

overrides:
  - files: ["**/*.scss"]
    customSyntax: "postcss-scss"
