status: ready
context:
  text:
    Lorem gibson 8-bit Freeside denim otaku sign boy neon warp long-chain hydrocarbons car.
    Lorem gibson realism tower pre-dome meta-artisanal tank-traps House of the Blue Lights
    count zero interrupt biochips garage drone derm/dermadisk suit galaxy wonton soup When It Changed faded Tokyo.
    Free-market count zero interrupt tattoo car courier assault vehicle Turing Registry film boat fluidity Legba soul-delay
    RAF industrial grade yiheyuan filters personality Shibuya gang weathered A.I. assassin.
