#!/usr/bin/env ruby
require "fileutils"
include FileUtils

# Delete old dist folder if it exists
rm_rf "dist"

commit = ENV["TRAVIS_COMMIT"]
tag = ENV.fetch("TRAVIS_TAG") { "HEAD" }
js_components_target = "dist/js/components"
release_filename = "innoq-styleguide-#{tag}.zip"
zip_blacklist = "-x #{File.read(".npmignore").gsub(/\n/, ' ')}"

exit 1 unless system("yarn run site")

cp_r "dist/site/assets", "dist/"

# Copy JavaScript components to dist so they can be imported more conveniently
mkdir_p js_components_target
Dir.glob("components/**/*.js").each do |f|
  cp f, js_components_target
end

cp_r "components", "dist/"
cp_r "lib/styles", "dist/sass"

File.write "dist/site/RELEASE.txt", commit

cd "dist" do
  exit 1 unless system("zip -r #{release_filename} . #{zip_blacklist}")
end

mv "./dist/#{release_filename}", "./"
