# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Release

on:
  push:
    branches: [main]
    tags:
      - v* # Our tags are prefixed with 'v'
  pull_request:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC npm Trusted Publishing https://docs.npmjs.com/trusted-publishers
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test

  deploy_site:
    if: ${{ contains(github.ref, 'refs/tags') }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run site
      - run: echo ${{ github.sha }} > dist/site/RELEASE.txt
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/site # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch

  publish:
    if: ${{ contains(github.ref, 'refs/tags') }}
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: ./scripts/dist
      - name: Publish to Node Packages
        run: npm publish
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: "@innoq-innoq-styleguide-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
